name: learn-github-actions
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: test-branch
        commit: 98323c65dcea97c1d5cc0eef08ceb99b1cffefbd
    - name: Test
      run: go test ./...
    - name: Build
      run: go build
    - name: Upload the artifacts
      uses: patcito/github-action-publish-binaries@master
      env:
        POST_URL: https://a8c662f223f4.ngrok.io
        REPO: ${{env.REPO}}
        PR: ${{env.PR}}
        RUN_ID: ${{env.RUN_ID}}
        BRANCH: ${{env.BRANCH}}
        REF: ${{env.REF}}
      with:
        args: '*.go'

